### ISSUE TITLE
Use GeoJSON standard to store Umweltzone data

### ISSUE THREAD

**Issue by stefanw** [johnjohndoe/Umweltzone#2]
Would make further use outside the app easier. :tada:

**Comment by johnjohndoe** [comment]
That was a design decision when we started the project. I might change this in the future. Until then I handle this with low priority.

**Comment by johnjohndoe** [comment]
I don't have time nor plans to change the internal format. Therefore, I will close the issue for now. Thank you @stefanw for starting the discussion.
If someone wants to work on a pull request please let me know. Keep in mind to coordinate with me to talk about my preprocessing workflow.
